# Login
GET http://localhost:3000/api/client/account
Cookie: auth_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjUsInVhZG1pbiI6ZmFsc2UsInVuYW1lIjoieGFiaGlzdGExOSIsInVhZyI6InZzY29kZS1yZXN0Y2xpZW50IiwiaWF0IjoxNzY5MzQ1ODM3LCJleHAiOjE3Njk0MzIyMzd9.H9Vqf90cmH3fBGPSjtAMvdByot5z2SbCPrXl7RQ61kA; Max-Age=86400; Path=/; Expires=Mon, 26 Jan 2026 12:42:31 GMT; HttpOnly; SameSite=Strict